### ISSUE TITLE
Not yet built

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.github.dariasteam.cowsrevenge#1]
It seems that godot engine has done something tricksy with their git between the last test build and the initial build and publish:

https://flathub.org/builds/#/builders/30/builds/115

We need to fix this before the app will be published.

**Comment by Dariasteam** [comment]
I think the problem is there are different commits for godot and godot-exports-templates in the json file. I changed it and now builds on my machine

**Comment by nedrichards** [comment]
Fixed by https://github.com/flathub/com.github.dariasteam.cowsrevenge/commit/f00fc5343ce3d90ebdeefd218af9d89fd5cef5a9
