### ISSUE TITLE
ERROR: load_interactive

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.dariasteam.cowsrevenge#2]
ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:1161.
ERROR: load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:210.

**Comment by Dariasteam** [comment]
I'm aware of them, been trying to solve since a long ago but can't figure out what is the problem. However, the game should run without any problems, isn't it?

**Comment by LeandroStanger** [comment]
Yes

**Comment by Dariasteam** [comment]
Ouch! So now it has become prioritary. I'm not sure where should I start, if the output it gives is the same for me but running good maybe the error isn't related to that. I'll try to look further in a couple of days. Have you had any problem with other godot engine game or with the tool itself?

**Comment by TingPing** [comment]
"Yes" sounds like it runs without problems.

**Comment by Dariasteam** [comment]
Well that would be great, @LeandroStanger?

**Comment by LeandroStanger** [comment]
@Dariasteam Cow's Revenge is working
