### ISSUE TITLE
Spain translation on flathub instead of english

### ISSUE THREAD

**Issue by Zlopez** [flathub/com.github.dariasteam.cowsrevenge#3]
Looking at the https://github.com/Dariasteam/Cows-Revenge/blob/master/linux_build/com.github.dariasteam.cowsrevenge.appdata.xml the file also contains English translation, but on the flathub page Spain translation is shown.

**Comment by AsciiWolf** [comment]
Same issue in GNOME Software. Spain translation is shown instead of the English one on my Fedora machine with Czech localization.

**Comment by TingPing** [comment]
This should be reported against https://github.com/flathub/linux-store-frontend

**Comment by Dariasteam** [comment]
Gonna try to fit the `appstream-util validate-strict` requirements just in case.

**Comment by jgarciao** [comment]
I don't know exactly how the process works but when an application is built the build process incorporates the appdata information from the application's source code to a file called appstream that has the information of all the applications in the flatpak repository.

Please, follow this steps and check the info for your application:
```
# Add the flathub repository and refresh the appstream information
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak update --appstream

# Extract this file and open a file called "data"
/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml.gz
```
You will find out that the information for your application is in Spanish. That's why the webapp, gnome-software and `flatpak search cow` shows the information in this language.

If the appdata was originally in Spanish in then you fixed to have different languages you might have to do a rebuild

**Comment by Dariasteam** [comment]
Checking some kde apsptrem files, it looks like translations are specified with `xml:lang=` instead of just `lang=` which I use. Also the `<description>` tag should only appear once. 

Hope https://github.com/Dariasteam/Cows-Revenge/commit/ad5ee76f011c4fa7eb7fcd5659c9a0945ab81e3b fixes this

**Comment by AsciiWolf** [comment]
There's still some unknown tag in the latest appdata file:
`$ appstream-util validate-strict com.github.dariasteam.cowsrevenge.appdata.xml`
`com.github.dariasteam.cowsrevenge.appdata.xml: FAILED:`
`• tag-invalid           : XML data contains unknown tag`
`Validation of files failed`

**Comment by Dariasteam** [comment]
Yep, I still don't know what could be the problem. Also makes me think appstream-util need urgently better outputs. Using `appstream-util validate-strict com.github.dariasteam.cowsrevenge.appdata.xml --verbose` could give the line or the tag itself but instead I only get:

```
(appstream-util:19921): As-DEBUG: 10:51:38.728: run appstream-util: validate-strict
com.github.dariasteam.cowsrevenge.appdata.xml: (appstream-util:19921): As-DEBUG: 10:51:38.813: Adding tag-invalid 'XML data contains unknown tag'
(appstream-util:19921): As-DEBUG: 10:51:38.813: checking https://i.imgur.com/w2aFnSV.jpg
(appstream-util:19921): As-DEBUG: 10:51:39.401: checking https://i.imgur.com/Ftj3Whe.png
(appstream-util:19921): As-DEBUG: 10:51:39.504: checking https://i.imgur.com/3E7w4HK.png
FAILED:
• tag-invalid           : XML data contains unknown tag
Validation of files failed
```

**Comment by Dariasteam** [comment]
Btw, does it mean the language problem is solved? I'm trying to check visiting flathub web localizing firefox with `LC_ALL="en_US" firefox` but I still see it in spanish

**Comment by AsciiWolf** [comment]
It seems it is unfortunately still not fixed.

**Comment by Dariasteam** [comment]
Appstream should be definitively fixed by https://github.com/Dariasteam/Cows-Revenge/commit/fe65838b2c77c594b7e46a59d910aadc8afcfe0b

**Comment by AsciiWolf** [comment]
It is still in Spanish on Flathub website and it looks like it is now missing in GNOME Software. :-( Maybe it just needs another rebuild?

**Comment by Dariasteam** [comment]
Mmmh maybe? I've rebuilt every time I've made changes but lets try once more. Although I'm suspecting that flathub itself doesn't show localized metadata but always english because Krita has translation for spanish in the source code but in flathub it shows english for me.

**Comment by jgarciao** [comment]
Right now the translations are not used in the website but it will be in
the future.

Today they are used in software app centers (Gnome Software, ...) and in
the command line (e.g. "flatpak search krita")

**Comment by Dariasteam** [comment]
I just do a rebuild and `flathub update` outputs `Error updating remote metadata for 'org.pipoypipagames.cowsrevenge-origin': Remote listing for org.pipoypipagames.cowsrevenge-origin not available; server has no summary file`

**Comment by Dariasteam** [comment]
Checking again the metadatafollowing this https://github.com/flathub/com.github.dariasteam.cowsrevenge/issues/3#issuecomment-386230534 now it has both languages as it should be. (But stil complains about summary file when updated)

**Comment by Dariasteam** [comment]
Well, flathub.org finally shows English translations. Now lets see what happen with the summary file and gnome-software

**Comment by Dariasteam** [comment]
Mhh.. the summary file is my local summary file from my local test repo.. :D forgive me everything

**Comment by Dariasteam** [comment]
plasma-discover shows it, i guess gnome-software will do or if not opening a new issue has more sense
