### ISSUE TITLE
Bluetooth gamepad doesn't work

### ISSUE THREAD

**Issue by Dariasteam** [flathub/com.github.dariasteam.cowsrevenge#4]
- I have no wired gamepad to test if them are affected too.
- Apparently is not a sandbox permission problem.

**Comment by TingPing** [comment]
It is a permission problem: `flatpak run --device=all com.github.dariasteam.cowsrevenge` should work.

**Comment by Dariasteam** [comment]
I must admit there is something inthe docs that really confuses me. I promise I searched before asking. Thank you so much once  more

**Comment by TingPing** [comment]
It isn't really documented anywhere because its.. evil. We don't have a sandbox solution for controllers.
